---

collabora_config:
  allowed_languages:
    - "de_DE"
    - "en_GB"
    - "en_US"

  network:
    # Protocol to use IPv4, IPv6 or all for both
    proto: IPv4
    # Listen address that coolwsd binds to. Can be 'any' or 'loopback'.
    listen: loopback
    # Allow/deny client IP address for POST(REST).
    post_allow:
      hosts: []
        # - description: "The IPv4 private 10.0.0.0/8 subnet (Podman)."
        #   network: '10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
        # - description: "Ditto, but as IPv4-mapped IPv6 addresses"
        #   network: '::ffff:10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'

    # Allowed hosts as an external data source inside edited files.
    # All allowed post_allow.host and storage.wopi entries are also considered to be
    # allowed as a data source.
    # Used for example in: PostMessage Action_InsertGraphics, =WEBSERVICE() function, external reference in the cell.
    lok_allow:
      hosts: []
        # - description: "Localhost access by name"
        #   network: 'localhost'
    content_security_policy: ""
    connection_timeout_secs: 30

...
